CREATE DATABASE IF NOT EXISTS ejercicio_ss;

USE ejercicio_ss;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '123456';

GRANT ALL PRIVILEGES ON ejercicio_ss.* TO 'admin'@'%';

FLUSH PRIVILEGES;